### ISSUE TITLE
how to build and run it on the spike?

### ISSUE THREAD

**Issue by Ddnirvana** [slavaim/riscv-magenta#1]
Hi slavaim,

 It's awesome to see that you have port zircon(magenta) to riscv!!!
 I want to try it on the spike, could you give me any instructions to do it?

Thanks a lot!

**Comment by slavaim** [comment]
Hi,
I used QEMU. Never tried with Spike.

**Comment by Ddnirvana** [comment]
@slavaim  thanks for you reply!

So have could I run it on the qemu? Which version of qemu should be used and which version of riscv privilege spec this project based on?

**Comment by slavaim** [comment]
QEMU emulator version 2.7.50
riscv64-unknown-linux-gnu-gcc (GCC) 6.1.0
RISC-V Priv Spec 1.9.1
